interface=wlp4s0
bind-interfaces
except-interface=lo
dhcp-authoritative
dhcp-range=10.99.0.20,10.99.0.80,255.255.255.0,1h
dhcp-option=3,10.99.0.1
dhcp-option=6,10.99.0.1
address=/#/10.99.0.1
domain-needed
bogus-priv
no-resolv
log-dhcp
log-queries
